import * as core from './corefix.js';

const app=document.querySelector('#app'), modal=document.querySelector('#modal'), toast=document.querySelector('#toast');
const STORE='ninochka-v4';
let state=load(), view={tab:'home',week:currentWeekIndex()}, planDraft=null, pendingPlan=null;
core.ensureCurrentMonth(state); save();

const dict={
ru:{title:'Семейный бюджет',home:'Главная',week:'Неделя',plan:'План',more:'Ещё',storage:'Хранилище',balance:'Сейчас на счёте',changeBalance:'Изменить баланс',history:'История',storageCurrency:'Валюта Хранилища',saved:'В плюс',savedMonth:'В этом месяце',savedAll:'За всё время',monthPlan:'План месяца',mandatory:'Обязательные',fourWeeks:'4 недели',reserve:'Резерв',openPlan:'Открыть план',weekFund:'Фонд недели',spent:'Потрачено',left:'Осталось',overspend:'Перерасход',openWeek:'Открыть неделю',expenses:'Расходы',addExpense:'Добавить расход',closeWeek:'Закрыть неделю',reopenWeek:'Открыть неделю снова',noExpenses:'Пока расходов нет',name:'Название',category:'Категория',amount:'Сумма',currency:'Валюта',save:'Сохранить',cancel:'Отмена',products:'Продукты',transport:'Транспорт',clothes:'Одежда',leisure:'Развлечения',other:'Другое',restaurant:'Например, ресторан',planIntro:'Здесь только план. Деньги из Хранилища не списываются.',housing:'Жильё',utilities:'Коммунальные',school:'Школа Никочки',addItem:'Добавить пункт',rates:'Курсы для плана',refreshRates:'Получить актуальные курсы',manualRate:'Можно поправить вручную',planTotal:'Всего запланировано',savePlan:'Сохранить план',settings:'Настройки',language:'Язык',theme:'Оформление',light:'Светлая',dark:'Тёмная',auto:'Авто',tutorial:'Показать обучение ещё раз',backup:'Резервная копия',export:'Экспорт данных',import:'Импорт данных',nb:'NB CURATED',nbHint:'Доход магазина. На семейный бюджет не влияет.',addIncome:'Добавить запись',currentMonth:'Текущий месяц',close:'Закрыть',storageHistory:'История Хранилища',setExact:'Указать точный баланс',adjust:'Добавить / вычесть',note:'Примечание',rateNeeded:'Нужен курс',rateAuto:'Актуальный курс',rateManual:'Ручной',weekClosed:'Неделя закрыта. Результат учтён в Хранилище.',weekOpened:'Неделя снова открыта. Предыдущий результат убран из Хранилища.',expenseAdded:'Расход добавлен',planSaved:'План сохранён',currencyChanged:'Валюта Хранилища изменена',next:'Дальше',start:'Начать',rateFail:'Не удалось получить курс. Можно ввести его вручную.',invalidMoney:'Проверь сумму',missingRate:'Сначала получи или введи курс',nameRequired:'Введи название',edit:'Изменить',delete:'Удалить',emptyHistory:'История пока пустая',weekN:'Неделя',todayWeek:'Текущая',closed:'Закрыта',open:'Открыта',setCurrencyHelp:'При смене валюты текущий баланс будет пересчитан по актуальному курсу.',custom:'Свой пункт',checkPlan:'Проверить итог',confirmPlan:'Сохранить план',ratesUpdated:'Курсы обновлены',
heroTitle:'Здесь всё спокойно и понятно.',heroCopy:'Смотри баланс, текущую неделю и расходы — всё главное рядом.',weekProgress:'Лимит недели',remainingPercent:'Осталось',prevWeek:'Предыдущая неделя',nextWeek:'Следующая неделя',storageWarm:'Под присмотром',storageWarmCopy:'Хранилище показывает реальный остаток. Пополняй или вычитай — и цифра всегда остаётся правдой.',
on1t:'Смотри главное',on1c:'Открывай приложение и сразу видишь Хранилище, текущую неделю и важные суммы. Ничего искать не нужно.',on2t:'Планируй неделю',on2c:'Задай фонд недели, проверь обязательные траты и оставь остальное в резерве. Зай, тут всё просто.',on3t:'Вноси расходы',on3c:'Выбирай категорию, сумму и валюту. Нажала «Сохранить» — всё посчиталось само.',on4t:'Для тебя, с заботой',on4c:'Пусть с деньгами будет меньше возни, а у нас — больше времени друг на друга. Я рядом. ❤️'},
