 const mm=m(), ww=w(); const spent=safe(()=>core.weekSpent(state,ww),0), fund=safe(()=>core.fundInStorage(state,ww),0), result=fund-spent;
 return `${top()}<section class="card"><div class="section-title"><div><div class="eyebrow">${tr('currentMonth')} · ${mm.id}</div><h2>${tr('weekN')} ${ww.id}</h2></div><span class="currency-pill">${ww.status==='closed'?tr('closed'):tr('open')}</span></div><div class="week-strip">${mm.weeks.map(x=>`<button class="week-chip ${x.id===ww.id?'active':''}" data-week="${x.id}">${x.id}</button>`).join('')}</div><div class="stats"><div class="stat"><span>${tr('weekFund')}</span><strong>${fmt(ww.fund.amount,ww.fund.currency)}</strong></div><div class="stat"><span>${tr('spent')}</span><strong>${safe(()=>fmt(spent),'—')}</strong></div><div class="stat"><span>${result<0?tr('overspend'):tr('left')}</span><strong class="${result<0?'negative':'positive'}">${safe(()=>fmt(Math.abs(result)),'—')}</strong></div></div></section>
 <section class="card"><div class="section-title"><h2>${tr('expenses')}</h2><button class="btn primary small" data-action="expense-add">＋ ${tr('addExpense')}</button></div><div class="list">${ww.expenses.length?ww.expenses.map(x=>`<div class="item"><div class="item-main"><strong>${escape(x.name)}</strong><small>${tr(x.category)||escape(x.category)} · ${x.currency}</small></div><div class="amount">${fmt(x.amount,x.currency)}</div><button class="btn small" data-action="expense-edit" data-id="${x.id}">✎</button></div>`).join(''):`<div class="empty">${tr('noExpenses')}</div>`}</div><div class="row" style="margin-top:16px">${ww.status==='closed'?`<button class="btn ghost grow" data-action="week-reopen">${tr('reopenWeek')}</button>`:`<button class="btn primary grow" data-action="week-close">${tr('closeWeek')}</button>`}</div></section>`}

function planPage(){
 const mm=m(); const ps=safe(()=>core.planSummary(state,mm),null); const used=new Set([state.storage.currency,...mm.obligations.map(x=>x.currency),...mm.weeks.map(x=>x.fund.currency)]); used.delete(state.storage.currency);
 return `${top()}<section class="card"><div class="section-title"><div><div class="eyebrow">${tr('monthPlan')}</div><h2>${mm.id}</h2></div></div><div class="note">${tr('planIntro')}</div></section>
 <section class="card"><div class="section-title"><h2>${tr('mandatory')}</h2><button class="btn small" data-action="obligation-add">＋ ${tr('addItem')}</button></div>${mm.obligations.map((x,i)=>planItem(x,i)).join('')}</section>
 <section class="card"><h2>${tr('fourWeeks')}</h2><div style="height:10px"></div>${mm.weeks.map(ww=>`<div class="plan-row"><label class="field name-field"><span>${tr('weekN')} ${ww.id}</span><input data-replace-on-focus name="fund-${ww.id}" inputmode="decimal" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" value="${core.moneyInput(ww.fund.amount)}"></label><label class="field"><span>${tr('currency')}</span><select name="fundcur-${ww.id}">${core.CURRENCIES.map(c=>`<option ${c===ww.fund.currency?'selected':''}>${c}</option>`).join('')}</select></label></div>`).join('')}</section>
 <section class="card"><div class="section-title"><h2>${tr('rates')}</h2><button class="btn small" data-action="rates-refresh">↻ ${tr('refreshRates')}</button></div>${[...used].map(c=>rateEditor(c)).join('')||`<div class="muted">${state.storage.currency}: 1 = 1</div>`}</section>
 <section class="card">${ps?`<div class="summary"><div class="summary-line"><span>${tr('mandatory')}</span><strong>${fmt(ps.mandatory)}</strong></div><div class="summary-line"><span>${tr('fourWeeks')}</span><strong>${fmt(ps.weekly)}</strong></div><div class="summary-line total"><span>${tr('planTotal')}</span><strong>${fmt(ps.total)}</strong></div><div class="summary-line"><span>${tr('reserve')}</span><strong class="${ps.reserve<0?'negative':'positive'}">${fmt(ps.reserve)}</strong></div></div>`:`<div class="note">${tr('missingRate')}</div>`}<button class="btn primary grow" style="width:100%;margin-top:16px" data-action="plan-save">${tr('savePlan')}</button></section>`}
function planItem(x,i){const label=x.name==='rent'?tr('housing'):x.name==='utilities'?tr('utilities'):x.name==='school'?tr('school'):x.name;return `<div class="plan-row" data-obligation="${x.id}"><label class="field name-field"><span>${tr('name')}</span><input data-replace-on-focus autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" name="oblname-${x.id}" value="${escape(label)}"></label><label class="field"><span>${tr('amount')}</span><input data-replace-on-focus inputmode="decimal" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" name="oblamount-${x.id}" value="${core.moneyInput(x.amount)}"></label><label class="field"><span>${tr('currency')}</span><select name="oblcur-${x.id}">${core.CURRENCIES.map(c=>`<option ${c===x.currency?'selected':''}>${c}</option>`).join('')}</select></label></div>`}
function rateEditor(c){const r=core.getRate(state,c,state.storage.currency);return `<div class="rate-box"><div><strong>1 ${c} = ${r?String(r):'—'} ${state.storage.currency}</strong><div class="muted">${r?tr('rateAuto'):tr('rateNeeded')} · ${tr('manualRate')}</div></div><div class="rate-line" style="margin-top:10px"><label class="field"><span>1 ${c} → ${state.storage.currency}</span><input data-replace-on-focus inputmode="decimal" autocomplete="off" name="rate-${c}" placeholder="${r||''}" value=""></label><button class="btn" data-action="rate-save" data-currency="${c}">${tr('save')}</button></div></div>`}

function morePage(){
 const nbTotal=state.nbEntries.reduce((s,x)=>s+(x.currency===state.storage.currency?x.amount:safe(()=>core.convert(state,x.amount,x.currency),0)),0);
 return `${top()}<section class="card"><div class="section-title"><div><div class="eyebrow">${tr('nb')}</div><h2>${fmt(nbTotal)}</h2></div><button class="btn small" data-action="nb-add">＋ ${tr('addIncome')}</button></div><div class="muted">${tr('nbHint')}</div>${state.nbEntries.slice(0,5).map(x=>`<div class="item" style="margin-top:10px"><div class="item-main"><strong>${escape(x.name)}</strong><small>${x.currency}</small></div><div class="amount">${fmt(x.amount,x.currency)}</div></div>`).join('')}</section>
 <section class="card"><h2>${tr('settings')}</h2><div class="settings-grid" style="margin-top:14px"><label class="field"><span>${tr('language')}</span><select data-setting="language"><option value="ru" ${lang()==='ru'?'selected':''}>Русский</option><option value="uk" ${lang()==='uk'?'selected':''}>Українська</option></select></label><div class="field"><span>${tr('theme')}</span><div class="segmented">${['light','dark','auto'].map(x=>`<button class="${state.preferences.theme===x?'active':''}" data-theme-choice="${x}">${tr(x)}</button>`).join('')}</div></div><button class="btn" data-action="tutorial">${tr('tutorial')}</button></div></section>
 <section class="card"><h2>${tr('backup')}</h2><div class="row wrap" style="margin-top:14px"><button class="btn" data-action="export">${tr('export')}</button><label class="btn ghost" style="display:inline-block">${tr('import')}<input type="file" id="import-file" accept="application/json,.json" hidden></label></div></section>`}

function render(){setDoc(); app.innerHTML=`<div class="app">${view.tab==='home'?home():view.tab==='week'?weekPage():view.tab==='plan'?planPage():morePage()}</div>${nav()}`; if(!state.preferences.onboardingSeen)renderOnboarding(0)}
function safe(fn,fallback){try{return fn()}catch{return fallback}}

function showModal(title,body){modal.innerHTML=`<div class="modal-head"><h2>${title}</h2><button class="close" data-action="modal-close">×</button></div><div class="modal-body">${body}</div>`;modal.showModal(); setTimeout(()=>modal.querySelector('input,select,button')?.focus(),20)}
function closeModal(){modal.close()}
function field(name,label,value='',opts=''){return `<label class="field"><span>${label}</span><input data-replace-on-focus autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" name="${name}" value="${escape(value)}" ${opts}></label>`}
function currencySelect(name,value){return `<label class="field"><span>${tr('currency')}</span><select name="${name}">${core.CURRENCIES.map(c=>`<option ${c===value?'selected':''}>${c}</option>`).join('')}</select></label>`}

function balanceModal(){showModal(tr('changeBalance'),`${field('amount',tr('amount'),'','inputmode="decimal" placeholder="0.00"')}${currencySelect('currency',state.storage.currency)}${field('note',tr('note'),'','placeholder="'+tr('note')+'"')}<div class="modal-actions"><button class="btn ghost" data-action="balance-exact">${tr('setExact')}</button><button class="btn primary" data-action="balance-adjust">${tr('adjust')}</button></div>`)}
