function expenseModal(item=null){const ww=w();showModal(item?tr('edit'):tr('addExpense'),`${field('name',tr('name'),item?.name||'','placeholder="'+tr('restaurant')+'"')}${field('amount',tr('amount'),item?core.moneyInput(item.amount):'','inputmode="decimal" placeholder="0.00"')}${currencySelect('currency',item?.currency||state.storage.currency)}<label class="field"><span>${tr('category')}</span><select name="category">${['products','transport','clothes','leisure','other'].map(c=>`<option ${item?.category===c?'selected':''} value="${c}">${tr(c)}</option>`).join('')}</select></label><div class="modal-actions">${item?`<button class="btn danger" data-action="expense-delete" data-id="${item.id}">${tr('delete')}</button>`:''}<button class="btn primary" data-action="expense-save" data-id="${item?.id||''}">${tr('save')}</button></div>`)}
function historyModal(){showModal(tr('storageHistory'),state.storage.history.length?`<div class="list">${state.storage.history.slice(0,50).map(x=>`<div class="item"><div class="item-main"><strong>${escape(x.note||x.type)}</strong><small>${new Date(x.date).toLocaleString()}</small></div><div class="amount ${x.converted<0?'negative':'positive'}">${x.converted!=null?fmt(x.converted):''}</div></div>`).join('')}</div>`:`<div class="empty-state"><img src="./assets/cat-data.svg" alt=""><strong>${tr('emptyHistory')}</strong></div>`)}
function settingsModal(){showModal(tr('settings'),`<label class="field"><span>${tr('language')}</span><select data-setting="language"><option value="ru" ${lang()==='ru'?'selected':''}>Русский</option><option value="uk" ${lang()==='uk'?'selected':''}>Українська</option></select></label><label class="field"><span>${tr('theme')}</span><select data-setting="theme"><option value="light" ${state.preferences.theme==='light'?'selected':''}>${tr('light')}</option><option value="dark" ${state.preferences.theme==='dark'?'selected':''}>${tr('dark')}</option><option value="auto" ${state.preferences.theme==='auto'?'selected':''}>${tr('auto')}</option></select></label><div class="note">${tr('setCurrencyHelp')}</div><button class="btn" style="margin-top:12px" data-action="tutorial">${tr('tutorial')}</button>`)}
function nbModal(){showModal(tr('addIncome'),`${field('name',tr('name'),'','placeholder="NB CURATED"')}${field('amount',tr('amount'),'','inputmode="decimal" placeholder="0.00"')}${currencySelect('currency',state.storage.currency)}<div class="modal-actions"><button class="btn primary" data-action="nb-save">${tr('save')}</button></div>`)}

function renderOnboarding(i){
  document.querySelector('.onboarding')?.remove();
  const slides=[['on1t','on1c','home'],['on2t','on2c','plan'],['on3t','on3c','week'],['on4t','on4c','love']];
  const [tk,ck,type]=slides[i];
  const art=type==='plan'?'<img src="./assets/cat-pencil.svg" alt="">':type==='week'?'<img src="./assets/cat-data.svg" alt="">':'';
  const el=document.createElement('div');el.className='onboarding';
  el.innerHTML=`<div class="onboard-inner"><div class="onboard-card"><div class="onboard-art ${type}">${art}</div><div class="onboard-copy"><div class="eyebrow">${i+1} / 4</div><h1>${tr(tk)}</h1><p>${tr(ck)}</p><div class="dots">${slides.map((_,j)=>`<span class="dot ${j===i?'active':''}"></span>`).join('')}</div><button class="btn primary" style="width:100%" data-onboard="${i<3?i+1:'done'}">${i<3?tr('next'):tr('start')}</button></div></div></div>`;
  document.body.append(el)
}

async function fetchRate(from,to){if(from===to)return 1;const ctrl=new AbortController();const t=setTimeout(()=>ctrl.abort(),8000);try{const r=await fetch(`https://api.frankfurter.dev/v2/rate/${from.toLowerCase()}/${to.toLowerCase()}`,{signal:ctrl.signal,cache:'no-store'});if(!r.ok)throw 0;const d=await r.json();if(!Number.isFinite(d.rate)||d.rate<=0)throw 0;core.setRate(state,from,to,d.rate,'automatic',d.date);return d.rate}finally{clearTimeout(t)}}
function applyCurrentRatesToPlan(){const mm=m();for(const item of mm.obligations){item.rate=item.currency===state.storage.currency?1:core.getRate(state,item.currency,state.storage.currency)}for(const ww of mm.weeks){ww.fund.rate=ww.fund.currency===state.storage.currency?1:core.getRate(state,ww.fund.currency,state.storage.currency)}}
async function refreshPlanRates(){planDraft=capturePlanDraft();try{await preparePlanRates(planDraft,{force:true});applyCurrentRatesToPlan();persist(tr('ratesUpdated'))}catch{notify(tr('rateFail'));render()}}
async function ensureRateFor(currency){if(currency===state.storage.currency)return 1;let r=core.getRate(state,currency,state.storage.currency);if(r)return r;try{return await fetchRate(currency,state.storage.currency)}catch{throw new Error(`missing_rate:${currency}:${state.storage.currency}`)}}
async function storageCurrencyChange(next){const old=state.storage.currency;if(next===old)return;try{const r=await fetchRate(old,next);core.changeStorageCurrency(state,next,r);await refreshPlanRates();persist(tr('currencyChanged'))}catch{showModal(tr('storageCurrency'),`<div class="note">${tr('rateFail')}</div>${field('rate',`1 ${old} = … ${next}`,'','inputmode="decimal" placeholder="1.00"')}<div class="modal-actions"><button class="btn primary" data-action="currency-manual" data-from="${old}" data-to="${next}">${tr('save')}</button></div>`)} }
function readModal(){return Object.fromEntries(new FormData(wrapForm(modal)).entries())}
function wrapForm(root){let f=root.querySelector('form');if(f)return f;f=document.createElement('form');[...root.querySelectorAll('input,select,textarea')].forEach(x=>f.append(x.cloneNode(true)));return f}
function val(name){return modal.querySelector(`[name="${CSS.escape(name)}"]`)?.value??''}
function errorMessage(e){const s=String(e?.message||e);if(s==='invalid_money')return tr('invalidMoney');if(s==='name_required')return tr('nameRequired');if(s.startsWith('missing_rate:'))return tr('missingRate');if(s==='storage_write_failed')return lang()==='uk'?'Не вдалося зберегти витрату':'Не удалось сохранить расход';return s}

async function handleAction(action,el){try{
 if(action==='settings')return settingsModal(); if(action==='modal-close')return closeModal(); if(action==='balance')return balanceModal(); if(action==='history')return historyModal(); if(action==='expense-add')return expenseModal(); if(action==='tutorial'){closeModal();state.preferences.onboardingSeen=false;save();return render()}
 if(action==='balance-adjust'){await ensureRateFor(val('currency'));core.adjustStorage(state,val('amount'),val('currency'),val('note'));closeModal();return persist()}
 if(action==='balance-exact'){await ensureRateFor(val('currency'));core.setStorageBalance(state,val('amount'),val('currency'),val('note'));closeModal();return persist()}
 if(action==='expense-save'){const category=val('category')||'other';const enteredName=String(val('name')||'').trim();const data={name:enteredName||tr(category),amount:val('amount'),currency:val('currency'),category};await ensureRateFor(data.currency);const targetWeek=w();const beforeCount=targetWeek.expenses.length;let savedId=el.dataset.id||'';if(savedId){core.updateExpense(state,targetWeek,savedId,data)}else{const created=core.addExpense(state,targetWeek,data);savedId=created.id;created.actor=state.preferences.actor==='volodymyr'?'volodymyr':'nina'}save();const raw=localStorage.getItem(STORE);if(!raw)throw new Error('storage_write_failed');const check=JSON.parse(raw);const savedWeek=check?.months?.find(x=>x.id===m().id)?.weeks?.find(x=>x.id===targetWeek.id);if(!savedWeek||savedWeek.expenses?.length<beforeCount||!savedWeek.expenses?.some(x=>x.id===savedId))throw new Error('storage_write_failed');closeModal();render();notify(tr('expenseAdded'));return}
 if(action==='expense-edit'){const item=w().expenses.find(x=>x.id===el.dataset.id);return expenseModal(item)}
 if(action==='expense-delete'){core.deleteExpense(state,w(),el.dataset.id);closeModal();return persist()}
 if(action==='week-close'){core.closeWeek(state,w());return persist(tr('weekClosed'))} if(action==='week-reopen'){core.reopenWeek(state,w());return persist(tr('weekOpened'))}
 if(action==='rates-refresh'){await refreshPlanRates();return}
 if(action==='rate-save'){const c=el.dataset.currency;const v=document.querySelector(`[name="rate-${c}"]`)?.value||'';core.setRate(state,c,state.storage.currency,v,'manual');applyCurrentRatesToPlan();return persist()}
 if(action==='plan-preview'){await previewPlan();return}
 if(action==='plan-confirm'){if(!pendingPlan)return;applyDraftTo(state,pendingPlan);planDraft=null;pendingPlan=null;closeModal();return persist(tr('planSaved'))}
 if(action==='obligation-add'){m().obligations.push({id:core.uid(),kind:'custom',name:tr('custom'),amount:0,currency:state.storage.currency,rate:1});return persist()}
 if(action==='nb-add')return nbModal(); if(action==='nb-save'){await ensureRateFor(val('currency'));core.addNb(state,{name:val('name'),amount:val('amount'),currency:val('currency')});closeModal();return persist()}
