 const mm=m(), ww=w(); const spent=safe(()=>core.weekSpent(state,ww),0), fund=safe(()=>core.fundInStorage(state,ww),0), result=fund-spent;
 const prevDisabled=ww.id<=mm.weeks[0].id?'disabled':'', nextDisabled=ww.id>=mm.weeks.at(-1).id?'disabled':'';
 return `${top()}<section class="card week-shell"><div class="week-heading"><button class="week-arrow" data-week-step="-1" aria-label="${tr('prevWeek')}" ${prevDisabled}>‹</button><div><div class="eyebrow">${tr('currentMonth')} · ${mm.id}</div><h1>${tr('weekN')} ${ww.id}</h1><span class="status-pill ${ww.status==='closed'?'is-closed':'is-open'}">${ww.status==='closed'?tr('closed'):tr('open')}</span></div><button class="week-arrow" data-week-step="1" aria-label="${tr('nextWeek')}" ${nextDisabled}>›</button></div><div class="week-strip">${mm.weeks.map(x=>`<button class="week-chip ${x.id===ww.id?'active':''}" data-week="${x.id}">${x.id}</button>`).join('')}</div><div class="week-fund-line"><div><span>${tr('weekFund')}</span><strong>${fundOriginal(ww)}</strong>${ww.fund.currency!==state.storage.currency?`<small>≈ ${fmt(fund)}</small>`:''}</div><div class="week-left"><span>${result<0?tr('overspend'):tr('left')}</span><strong class="${result<0?'negative':'positive'}">${fmt(Math.abs(result))}</strong></div></div>${progressHTML(spent,fund)}<div class="stats compact"><div class="stat"><span>${tr('spent')}</span><strong>${fmt(spent)}</strong></div><div class="stat"><span>${result<0?tr('overspend'):tr('remainingPercent')}</span><strong class="${result<0?'negative':'positive'}">${fmt(Math.abs(result))}</strong></div><div class="stat"><span>${tr('weekProgress')}</span><strong>${Math.round(progressInfo(spent,fund).raw)}%</strong></div></div></section>
 <section class="card expenses-card"><div class="section-title"><h2>${tr('expenses')}</h2><button class="btn primary small" data-action="expense-add">＋ ${tr('addExpense')}</button></div><div class="list">${ww.expenses.length?ww.expenses.map(x=>`<div class="item expense-item"><div class="category-icon">${categoryIcon(x.category)}</div><div class="item-main"><strong>${escape(x.name)}</strong><small>${tr(x.category)||escape(x.category)} · ${x.currency}</small></div><div class="amount">${fmt(x.amount,x.currency)}</div><button class="edit-btn" data-action="expense-edit" data-id="${x.id}" aria-label="${tr('edit')}">✎</button></div>`).join(''):`<div class="empty-state"><img src="./assets/cat-weekly.svg" alt=""><strong>${tr('noExpenses')}</strong><span>${lang()==='uk'?'Додай першу витрату — далі все порахується саме.':'Добавь первый расход — дальше всё посчитается само.'}</span></div>`}</div><div class="row week-close-row">${ww.status==='closed'?`<button class="btn ghost grow" data-action="week-reopen">${tr('reopenWeek')}</button>`:`<button class="btn primary grow" data-action="week-close">${tr('closeWeek')}</button>`}</div></section>`}

function capturePlanDraft(){
 const mm=m(), d={obligations:{},funds:{},manualRates:{}};
 for(const x of mm.obligations){d.obligations[x.id]={name:document.querySelector(`[name="oblname-${x.id}"]`)?.value ?? (x.name==='rent'?tr('housing'):x.name==='utilities'?tr('utilities'):x.name==='school'?tr('school'):x.name),amount:document.querySelector(`[name="oblamount-${x.id}"]`)?.value ?? core.moneyInput(x.amount),currency:document.querySelector(`[name="oblcur-${x.id}"]`)?.value ?? x.currency}}
 for(const ww of mm.weeks){d.funds[ww.id]={amount:document.querySelector(`[name="fund-${ww.id}"]`)?.value ?? core.moneyInput(ww.fund.amount),currency:document.querySelector(`[name="fundcur-${ww.id}"]`)?.value ?? ww.fund.currency}}
 document.querySelectorAll('[name^="rate-"]').forEach(input=>{if(input.value.trim())d.manualRates[input.name.slice(5)]=input.value.trim()});
 return d;
}
function draftCurrencies(d){const set=new Set([state.storage.currency]);Object.values(d?.obligations||{}).forEach(x=>set.add(x.currency));Object.values(d?.funds||{}).forEach(x=>set.add(x.currency));set.delete(state.storage.currency);return set}
function planDraftValue(group,id,key,fallback){return planDraft?.[group]?.[id]?.[key] ?? fallback}
function applyDraftTo(target,d){const mm=core.month(target,core.nowMonth());for(const x of mm.obligations){const v=d.obligations[x.id];if(!v)continue;const systemLabel=x.name==='rent'?tr('housing'):x.name==='utilities'?tr('utilities'):x.name==='school'?tr('school'):null;const nextName=systemLabel&&v.name.trim()===systemLabel?x.name:v.name.trim();core.upsertObligation(target,mm,{...x,name:nextName,amount:v.amount,currency:v.currency})}for(const ww of mm.weeks){const v=d.funds[ww.id];if(v)core.setWeekFund(target,ww,v.amount,v.currency)}return mm}
async function preparePlanRates(d,{force=false}={}){for(const [c,v] of Object.entries(d.manualRates||{}))core.setRate(state,c,state.storage.currency,v,'manual');for(const c of draftCurrencies(d)){if(d.manualRates?.[c]&&!force)continue;try{await fetchRate(c,state.storage.currency)}catch{if(!core.getRate(state,c,state.storage.currency))throw new Error(`missing_rate:${c}:${state.storage.currency}`)}}save()}
async function previewPlan(){planDraft=capturePlanDraft();await preparePlanRates(planDraft);const temp=structuredClone(state), tm=applyDraftTo(temp,planDraft), totals=core.planSummary(temp,tm);pendingPlan=structuredClone(planDraft);showModal(tr('monthPlan'),`<div class="summary"><div class="summary-line"><span>${tr('mandatory')}</span><strong>${fmt(totals.mandatory)}</strong></div><div class="summary-line"><span>${tr('fourWeeks')}</span><strong>${fmt(totals.weekly)}</strong></div><div class="summary-line total"><span>${tr('planTotal')}</span><strong>${fmt(totals.total)}</strong></div><div class="summary-line"><span>${tr('reserve')}</span><strong class="${totals.reserve<0?'negative':'positive'}">${fmt(totals.reserve)}</strong></div></div><div class="modal-actions"><button class="btn primary" data-action="plan-confirm">${tr('confirmPlan')}</button></div>`)}

function planPage(){
 const mm=m(); const ps=safe(()=>core.planSummary(state,mm),null); const used=planDraft?draftCurrencies(planDraft):new Set([state.storage.currency,...mm.obligations.map(x=>x.currency),...mm.weeks.map(x=>x.fund.currency)]); used.delete(state.storage.currency);
 return `${top()}<section class="card plan-hero"><div><div class="eyebrow">${tr('monthPlan')}</div><h1>${mm.id}</h1><p>${tr('planIntro')}</p></div><img src="./assets/cat-pencil.svg" alt=""></section>
 <section class="card"><div class="section-title"><h2>${tr('mandatory')}</h2><button class="btn small" data-action="obligation-add">＋ ${tr('addItem')}</button></div>${mm.obligations.map((x,i)=>planItem(x,i)).join('')}</section>
 <section class="card"><h2>${tr('fourWeeks')}</h2><div style="height:10px"></div>${mm.weeks.map(ww=>`<div class="plan-row"><label class="field name-field"><span>${tr('weekN')} ${ww.id}</span><input data-replace-on-focus name="fund-${ww.id}" inputmode="decimal" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" value="${escape(planDraftValue('funds',ww.id,'amount',core.moneyInput(ww.fund.amount)))}"></label><label class="field"><span>${tr('currency')}</span><select name="fundcur-${ww.id}">${core.CURRENCIES.map(c=>`<option ${c===planDraftValue('funds',ww.id,'currency',ww.fund.currency)?'selected':''}>${c}</option>`).join('')}</select></label></div>`).join('')}</section>
 <section class="card"><div class="section-title"><h2>${tr('rates')}</h2><button class="btn small" data-action="rates-refresh">↻ ${tr('refreshRates')}</button></div>${[...used].map(c=>rateEditor(c)).join('')||`<div class="muted">${state.storage.currency}: 1 = 1</div>`}</section>
 <section class="card">${ps?`<div class="summary"><div class="summary-line"><span>${tr('mandatory')}</span><strong>${fmt(ps.mandatory)}</strong></div><div class="summary-line"><span>${tr('fourWeeks')}</span><strong>${fmt(ps.weekly)}</strong></div><div class="summary-line total"><span>${tr('planTotal')}</span><strong>${fmt(ps.total)}</strong></div><div class="summary-line"><span>${tr('reserve')}</span><strong class="${ps.reserve<0?'negative':'positive'}">${fmt(ps.reserve)}</strong></div></div>`:`<div class="note">${tr('missingRate')}</div>`}<button class="btn primary grow" style="width:100%;margin-top:16px" data-action="plan-preview">${tr('checkPlan')}</button></section>`}
function planItem(x,i){const label=x.name==='rent'?tr('housing'):x.name==='utilities'?tr('utilities'):x.name==='school'?tr('school'):x.name, name=planDraftValue('obligations',x.id,'name',label), amount=planDraftValue('obligations',x.id,'amount',core.moneyInput(x.amount)), currency=planDraftValue('obligations',x.id,'currency',x.currency);return `<div class="plan-row" data-obligation="${x.id}"><label class="field name-field"><span>${tr('name')}</span><input data-replace-on-focus autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" name="oblname-${x.id}" value="${escape(name)}"></label><label class="field"><span>${tr('amount')}</span><input data-replace-on-focus inputmode="decimal" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" name="oblamount-${x.id}" value="${escape(amount)}"></label><label class="field"><span>${tr('currency')}</span><select name="oblcur-${x.id}">${core.CURRENCIES.map(c=>`<option ${c===currency?'selected':''}>${c}</option>`).join('')}</select></label></div>`}
function rateEditor(c){const r=core.getRate(state,c,state.storage.currency);return `<div class="rate-box"><div><strong>1 ${c} = ${r?String(r):'—'} ${state.storage.currency}</strong><div class="muted">${r?tr('rateAuto'):tr('rateNeeded')} · ${tr('manualRate')}</div></div><div class="rate-line" style="margin-top:10px"><label class="field"><span>1 ${c} → ${state.storage.currency}</span><input data-replace-on-focus inputmode="decimal" autocomplete="off" name="rate-${c}" placeholder="${r||''}" value=""></label><button class="btn" data-action="rate-save" data-currency="${c}">${tr('save')}</button></div></div>`}

function morePage(){
 const nbTotal=state.nbEntries.reduce((s,x)=>s+(x.currency===state.storage.currency?x.amount:safe(()=>core.convert(state,x.amount,x.currency),0)),0);
 return `${top()}<section class="card more-hero"><img src="./assets/cat-currencies.svg" alt=""><div><div class="eyebrow">${tr('nb')}</div><h2>${fmt(nbTotal)}</h2><p>${tr('nbHint')}</p></div><button class="btn small" data-action="nb-add">＋ ${tr('addIncome')}</button></section>
 <section class="card"><h2>${tr('settings')}</h2><div class="settings-grid" style="margin-top:14px"><label class="field"><span>${tr('language')}</span><select data-setting="language"><option value="ru" ${lang()==='ru'?'selected':''}>Русский</option><option value="uk" ${lang()==='uk'?'selected':''}>Українська</option></select></label><div class="field"><span>${tr('theme')}</span><div class="segmented">${['light','dark','auto'].map(x=>`<button class="${state.preferences.theme===x?'active':''}" data-theme-choice="${x}">${tr(x)}</button>`).join('')}</div></div><button class="btn" data-action="tutorial">${tr('tutorial')}</button></div></section>
 <section class="card"><h2>${tr('backup')}</h2><div class="row wrap" style="margin-top:14px"><button class="btn" data-action="export">${tr('export')}</button><label class="btn ghost" style="display:inline-block">${tr('import')}<input type="file" id="import-file" accept="application/json,.json" hidden></label></div></section>`}

function render(){setDoc(); app.innerHTML=`<div class="app">${view.tab==='home'?home():view.tab==='week'?weekPage():view.tab==='plan'?planPage():morePage()}</div>${nav()}`; if(!state.preferences.onboardingSeen)renderOnboarding(0)}
function safe(fn,fallback){try{return fn()}catch{return fallback}}

function showModal(title,body){modal.innerHTML=`<div class="modal-head"><h2>${title}</h2><button class="close" data-action="modal-close">×</button></div><div class="modal-body">${body}</div>`;modal.showModal(); setTimeout(()=>modal.querySelector('input,select,button')?.focus(),20)}
function closeModal(){if(modal.open)modal.close()}
function field(name,label,value='',opts=''){return `<label class="field"><span>${label}</span><input data-replace-on-focus autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" name="${name}" value="${escape(value)}" ${opts}></label>`}
function currencySelect(name,value){return `<label class="field"><span>${tr('currency')}</span><select name="${name}">${core.CURRENCIES.map(c=>`<option ${c===value?'selected':''}>${c}</option>`).join('')}</select></label>`}

function balanceModal(){showModal(tr('changeBalance'),`${field('amount',tr('amount'),'','inputmode="decimal" placeholder="0.00"')}${currencySelect('currency',state.storage.currency)}${field('note',tr('note'),'','placeholder="'+tr('note')+'"')}<div class="modal-actions"><button class="btn ghost" data-action="balance-exact">${tr('setExact')}</button><button class="btn primary" data-action="balance-adjust">${tr('adjust')}</button></div>`)}
